# Generated by Django 4.0 on 2022-04-28 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_created', models.DateTimeField(auto_now_add=True, verbose_name='время создания')),
                ('datetime_updated', models.DateTimeField(auto_now=True, verbose_name='время обновления')),
                ('datetime_deleted', models.DateTimeField(blank=True, null=True, verbose_name='время удаления')),
                ('studio', models.CharField(max_length=100, verbose_name='Студия')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Аниме',
                'verbose_name_plural': 'Аниме',
                'ordering': ('-datetime_created',),
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_en', models.TextField(default='', verbose_name='Описание (Англ)')),
                ('text_ru', models.TextField(default='', verbose_name='Описание (Рус)')),
            ],
            options={
                'verbose_name': 'Описание',
                'verbose_name_plural': 'Описания',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='ReleaseDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('published', models.CharField(max_length=20, verbose_name='Выпущен')),
                ('date', models.DateTimeField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата выпуска',
                'verbose_name_plural': 'Даты выпуска',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('link', models.TextField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Наименование',
                'verbose_name_plural': 'Наименования',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя')),
                ('anime', models.ManyToManyField(related_name='genres', to='anime.Anime', verbose_name='аниме')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='anime',
            name='description',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anime.description', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='anime',
            name='release_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anime.releasedate', verbose_name='Дата выпуска'),
        ),
        migrations.AddField(
            model_name='anime',
            name='title',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='anime.title', verbose_name='Название'),
        ),
    ]
